version : '3.8'
services:
    mysql:
        image: mysql:8.0.2
        environment: 
            MYSQL_ROOT_PASSWORD: supersecretpw
            MYSQL_DATABASE: final_project
        ports:
            - "3300:3306"

